name: Luraph Deobfuscation and Bytecode Conversion

on:
  push:
    branches:
      - main

jobs:
  deobfuscate_and_convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1" # or any compatible version

      - name: Install LuraphDeobfuscator
        run: |
          git clone https://github.com/PhoenixZeng/LuraphDeobfuscator.git
          # Check the LuraphDeobfuscator readme for any build steps or dependencies.
          # If there are any, add them here.
          # Example:
          # cd LuraphDeobfuscator
          # make
          # cd ..

      - name: Deobfuscate Luraph script
        run: |
          lua LuraphDeobfuscator/deobfuscator.lua luraph_script.lua > deobfuscated_script.lua # Replace luraph_script.lua

      - name: Compile Lua to bytecode
        run: |
          luac -o bytecode.luac deobfuscated_script.lua

      - name: Decompile bytecode with Unluac
        run: |
          sudo apt-get update
          sudo apt-get install -y unluac
          unluac bytecode.luac > decompiled_script.lua

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deobfuscated_script.lua
            bytecode.luac
            decompiled_script.lua
          tag_name: "Luraph-Deobfuscated-Release-${{ github.run_id }}"
          name: "Luraph Deobfuscated Release ${{ github.run_id }}"
          body: "Release of Luraph deobfuscated lua and bytecode."
