name: Luraph Deobfuscation and Bytecode Conversion

on:
  push:
    branches:
      - main

jobs:
  deobfuscate_and_convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1" # Adjust if needed

      - name: Install LuraphDeobfuscator Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          # Check LuraphDeobfuscator README for any specific dependencies.
          # Example (if needed):
          # sudo apt-get install -y some-dependency

      - name: Install LuraphDeobfuscator
        run: |
          git clone https://github.com/PhoenixZeng/LuraphDeobfuscator.git
          cd LuraphDeobfuscator
          # No explicit build instructions found in the README.
          # If a build is required, add commands here.
          cd ..

      - name: Deobfuscate Luraph script (Butter.lua)
        run: |
          lua LuraphDeobfuscator/deobfuscator.lua Butter.lua > deobfuscated_script.lua || { echo "Luraph deobfuscation failed!"; exit 1; }

      - name: Compile Lua to bytecode
        run: |
          luac -o bytecode.luac deobfuscated_script.lua || { echo "Lua compilation failed!"; exit 1; }

      - name: Decompile bytecode with Unluac
        run: |
          sudo apt-get update
          sudo apt-get install -y unluac
          unluac bytecode.luac > decompiled_script.lua || { echo "Unluac decompilation failed!"; exit 1; }

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deobfuscated_script.lua
            bytecode.luac
            decompiled_script.lua
          tag_name: "Luraph-Deobfuscated-Release-${{ github.run_id }}"
          name: "Luraph Deobfuscated Release ${{ github.run_id }}"
          body: "Release of Luraph deobfuscated lua and bytecode."
